// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SQLPerformaceAndORMsDemo
{
    [Table("Customer")]
    [Index(nameof(SupportRepId), Name = "IFK_CustomerSupportRepId")]
    public partial class Customer
    {
        public Customer()
        {
            Invoices = new ObservableCollection<Invoice>();
        }

        [Key]
        public virtual int CustomerId { get; set; }
        [Required]
        [StringLength(40)]
        public virtual string FirstName { get; set; }
        [Required]
        [StringLength(20)]
        public virtual string LastName { get; set; }
        [StringLength(80)]
        public virtual string Company { get; set; }
        [StringLength(70)]
        public virtual string Address { get; set; }
        [StringLength(40)]
        public virtual string City { get; set; }
        [StringLength(40)]
        public virtual string State { get; set; }
        [StringLength(40)]
        public virtual string Country { get; set; }
        [StringLength(10)]
        public virtual string PostalCode { get; set; }
        [StringLength(24)]
        public virtual string Phone { get; set; }
        [StringLength(24)]
        public virtual string Fax { get; set; }
        [Required]
        [StringLength(60)]
        public virtual string Email { get; set; }
        public virtual int? SupportRepId { get; set; }

        [ForeignKey(nameof(SupportRepId))]
        [InverseProperty(nameof(Employee.Customers))]
        public virtual Employee SupportRep { get; set; }
        [InverseProperty(nameof(Invoice.Customer))]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}