// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SQLPerformaceAndORMsDemo
{
    [Table("Employee")]
    [Index(nameof(ReportsTo), Name = "IFK_EmployeeReportsTo")]
    public partial class Employee
    {
        public Employee()
        {
            Customers = new ObservableCollection<Customer>();
            InverseReportsToNavigation = new ObservableCollection<Employee>();
        }

        [Key]
        public virtual int EmployeeId { get; set; }
        [Required]
        [StringLength(20)]
        public virtual string LastName { get; set; }
        [Required]
        [StringLength(20)]
        public virtual string FirstName { get; set; }
        [StringLength(30)]
        public virtual string Title { get; set; }
        public virtual int? ReportsTo { get; set; }
        [Column(TypeName = "datetime")]
        public virtual DateTime? BirthDate { get; set; }
        [Column(TypeName = "datetime")]
        public virtual DateTime? HireDate { get; set; }
        [StringLength(70)]
        public virtual string Address { get; set; }
        [StringLength(40)]
        public virtual string City { get; set; }
        [StringLength(40)]
        public virtual string State { get; set; }
        [StringLength(40)]
        public virtual string Country { get; set; }
        [StringLength(10)]
        public virtual string PostalCode { get; set; }
        [StringLength(24)]
        public virtual string Phone { get; set; }
        [StringLength(24)]
        public virtual string Fax { get; set; }
        [StringLength(60)]
        public virtual string Email { get; set; }

        [ForeignKey(nameof(ReportsTo))]
        [InverseProperty(nameof(Employee.InverseReportsToNavigation))]
        public virtual Employee ReportsToNavigation { get; set; }
        [InverseProperty(nameof(Customer.SupportRep))]
        public virtual ICollection<Customer> Customers { get; set; }
        [InverseProperty(nameof(Employee.ReportsToNavigation))]
        public virtual ICollection<Employee> InverseReportsToNavigation { get; set; }
    }
}