// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SQLPerformaceAndORMsDemo
{
    [Table("InvoiceLine")]
    [Index(nameof(InvoiceId), Name = "IFK_InvoiceLineInvoiceId")]
    [Index(nameof(TrackId), Name = "IFK_InvoiceLineTrackId")]
    public partial class InvoiceLine
    {
        [Key]
        public virtual int InvoiceLineId { get; set; }
        public virtual int InvoiceId { get; set; }
        public virtual int TrackId { get; set; }
        [Column(TypeName = "numeric(10, 2)")]
        public virtual decimal UnitPrice { get; set; }
        public virtual int Quantity { get; set; }

        [ForeignKey(nameof(InvoiceId))]
        [InverseProperty("InvoiceLines")]
        public virtual Invoice Invoice { get; set; }
        [ForeignKey(nameof(TrackId))]
        [InverseProperty("InvoiceLines")]
        public virtual Track Track { get; set; }
    }
}