// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SQLPerformaceAndORMsDemo
{
    [Table("Invoice")]
    [Index(nameof(CustomerId), Name = "IFK_InvoiceCustomerId")]
    public partial class Invoice
    {
        public Invoice()
        {
            InvoiceLines = new ObservableCollection<InvoiceLine>();
        }

        [Key]
        public virtual int InvoiceId { get; set; }
        public virtual int CustomerId { get; set; }
        [Column(TypeName = "datetime")]
        public virtual DateTime InvoiceDate { get; set; }
        [StringLength(70)]
        public virtual string BillingAddress { get; set; }
        [StringLength(40)]
        public virtual string BillingCity { get; set; }
        [StringLength(40)]
        public virtual string BillingState { get; set; }
        [StringLength(40)]
        public virtual string BillingCountry { get; set; }
        [StringLength(10)]
        public virtual string BillingPostalCode { get; set; }
        [Column(TypeName = "numeric(10, 2)")]
        public virtual decimal Total { get; set; }

        [ForeignKey(nameof(CustomerId))]
        [InverseProperty("Invoices")]
        public virtual Customer Customer { get; set; }
        [InverseProperty(nameof(InvoiceLine.Invoice))]
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
    }
}