// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SQLPerformaceAndORMsDemo
{
    [Table("PlaylistTrack")]
    [Index(nameof(TrackId), Name = "IFK_PlaylistTrackTrackId")]
    public partial class PlaylistTrack
    {
        [Key]
        public virtual int PlaylistId { get; set; }
        [Key]
        public virtual int TrackId { get; set; }

        [ForeignKey(nameof(PlaylistId))]
        [InverseProperty("PlaylistTracks")]
        public virtual Playlist Playlist { get; set; }
        [ForeignKey(nameof(TrackId))]
        [InverseProperty("PlaylistTracks")]
        public virtual Track Track { get; set; }
    }
}